// Copyright 2026 The Cocomhub Authors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Package grpc provides a gRPC-based transport layer skeleton.
//
// Proto service definition (hand-written skeleton, protoc generation required for
// production use):
//
//	service Xfer {
//	    rpc Stream(stream XferMsg) returns (stream XferMsg);
//	}
//
// message XferMsg {
//	    bytes payload = 1;
//	}
//
// NOTE: This is a skeleton implementation. Dial returns "not yet implemented, use ws
// instead". Full implementation requires protoc-generated code from the proto above.
package grpc

import (
	"context"
	"fmt"
)

// ---------------------------------------------------------------------------
// Minimal xfer-compatible interfaces (defined inline so this module compiles
// independently of the main sproxy module's xfer transport registry).
// ---------------------------------------------------------------------------

// Conn is the interface for a bidirectional message-oriented transport
// connection, matching the contract in github.com/cocomhub/sproxy/pkg/tunnel/xfer.
type Conn interface {
	// Send sends a message over the connection.
	Send(ctx context.Context, msg []byte) error
	// Receive blocks and returns the next message from the connection.
	Receive(ctx context.Context) ([]byte, error)
	// Close closes the connection.
	Close() error
}

// Listener is the interface for accepting incoming connections.
type Listener interface {
	// Accept blocks until a new connection arrives.
	Accept(ctx context.Context) (Conn, error)
	// Close stops listening.
	Close() error
	// Addr returns the listener's network address.
	Addr() string
}

// Transport describes a transport implementation for registration.
type Transport struct {
	Name   string
	Dial   func(ctx context.Context, addr string) (Conn, error)
	Listen func(ctx context.Context, addr string) (Listener, error)
}

var registry = make(map[string]*Transport)

// Register registers a transport by name. Panics if name is empty, nil, or
// already registered.
func Register(t *Transport) {
	if t == nil {
		panic("grpc: Register called with nil Transport")
	}
	if t.Name == "" {
		panic("grpc: Register called with empty Name")
	}
	if _, exists := registry[t.Name]; exists {
		panic(fmt.Sprintf("grpc: duplicate transport name: %s", t.Name))
	}
	registry[t.Name] = t
}

// Get returns the registered Transport by name, or nil.
func Get(name string) *Transport {
	return registry[name]
}

func init() {
	Register(&Transport{
		Name:   "grpc",
		Dial:   Dial,
		Listen: Listen,
	})
}

// ---------------------------------------------------------------------------
// gRPC service skeleton (hand-written interface, no protoc dependency)
// ---------------------------------------------------------------------------

// XferMsg is the message type for the gRPC bidirectional stream.
// In production this would be generated from:
//
//	message XferMsg {
//	    bytes payload = 1;
//	}
type XferMsg struct {
	Payload []byte
}

// Xfer_StreamClient is the client side of the Xfer.Stream bidirectional RPC.
// In production this would be generated by protoc.
type Xfer_StreamClient interface {
	Send(*XferMsg) error
	Recv() (*XferMsg, error)
	CloseSend() error
	Context() context.Context
}

// Xfer_StreamServer is the server side of the Xfer.Stream bidirectional RPC.
type Xfer_StreamServer interface {
	Send(*XferMsg) error
	Recv() (*XferMsg, error)
	Context() context.Context
}

// XferServer is the interface that the gRPC server must implement.
type XferServer interface {
	Stream(Xfer_StreamServer) error
}

// ---------------------------------------------------------------------------
// grpcConn wraps a gRPC bidirectional stream as a Conn.
// ---------------------------------------------------------------------------

// grpcConn implements Conn over a gRPC bidirectional stream.
type grpcConn struct {
	client Xfer_StreamClient
}

// Send sends a message over the gRPC stream.
func (c *grpcConn) Send(ctx context.Context, msg []byte) error {
	return c.client.Send(&XferMsg{Payload: msg})
}

// Receive blocks and returns the next message from the gRPC stream.
func (c *grpcConn) Receive(ctx context.Context) ([]byte, error) {
	msg, err := c.client.Recv()
	if err != nil {
		return nil, err
	}
	return msg.Payload, nil
}

// Close closes the gRPC stream.
func (c *grpcConn) Close() error {
	return c.client.CloseSend()
}

// ---------------------------------------------------------------------------
// Dial and Listen (skeleton)
// ---------------------------------------------------------------------------

// Dial creates a new gRPC connection to the given address.
// Currently returns "not yet implemented, use ws instead".
func Dial(ctx context.Context, addr string) (Conn, error) {
	return nil, fmt.Errorf("grpc: not yet implemented, use ws instead")
}

// Listen starts a gRPC server on the given address and returns a Listener.
// Currently returns "not yet implemented, use ws instead".
func Listen(ctx context.Context, addr string) (Listener, error) {
	return nil, fmt.Errorf("grpc: not yet implemented, use ws instead")
}
