# Copyright 2026 The Cocomhub Authors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

sonar.projectKey=cocomhub_sproxy
sonar.organization=cocomhub
sonar.host.url=https://sonarcloud.io
sonar.go.coverage.reportPaths=build/cover.out
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=test/**,tools/**,build/**,xfer/grpc/**,xfer/webrtc/**,.claude/**,.trae/**,.cursor/**,fileclient.sh
