# Copyright 2026 The Cocomhub Authors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: sproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sproxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sproxy
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: sproxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 18083
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          volumeMounts:
            - name: storage
              mountPath: /app/storage
            {{- if .Values.config }}
            - name: config
              mountPath: /app/sproxy.yaml
              subPath: sproxy.yaml
              readOnly: true
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
            timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
            failureThreshold: {{ .Values.probe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.periodSeconds }}
            timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
            failureThreshold: {{ .Values.probe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "sproxy.fullname" . }}-storage
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.config }}
        - name: config
          configMap:
            name: {{ include "sproxy.fullname" . }}-config
        {{- end }}
