# Copyright 2026 The Cocomhub Authors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.ingress.enabled .Values.ingress.hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: sproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.certManager }}
    cert-manager.io/cluster-issuer: {{ required "ingress.tls.clusterIssuer 必填（certManager=true 时）" .Values.ingress.tls.clusterIssuer | quote }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ required "ingress.tls.secretName 必填（tls.enabled=true 时）" .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "sproxy.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
