# Copyright 2026 The Cocomhub Authors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sproxy.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: sproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{- if .Values.secret.tunnelKey }}
  SPROXY_TUNNEL_KEY: {{ .Values.secret.tunnelKey | quote }}
  {{- end }}
  {{- if .Values.secret.apiKeys }}
  SPROXY_API_KEYS: {{ .Values.secret.apiKeys | quote }}
  {{- end }}
  {{- if .Values.secret.metricsToken }}
  SPROXY_METRICS_TOKEN: {{ .Values.secret.metricsToken | quote }}
  {{- end }}
{{- end }}
