// Copyright 2026 The Cocomhub Authors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Package grpc provides a gRPC-based transport layer skeleton.
//
// Proto service definition (hand-written skeleton, protoc generation required for
// production use):
//
//	service Xfer {
//	    rpc Stream(stream XferMsg) returns (stream XferMsg);
//	}
//
//	message XferMsg {
//		    bytes payload = 1;
//		}
//
// NOTE: This is a skeleton implementation. Dial returns "not yet implemented, use ws
// instead". Full implementation requires protoc-generated code from the proto above.
package grpc

import (
	"context"
	"fmt"
	"net"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// ---------------------------------------------------------------------------
// Minimal xfer-compatible interfaces (defined inline so this module compiles
// independently of the main sproxy module's xfer transport registry).
// ---------------------------------------------------------------------------

// Conn is the interface for a bidirectional message-oriented transport
// connection, matching the contract in github.com/cocomhub/sproxy/pkg/tunnel/xfer.
type Conn interface {
	// Send sends a message over the connection.
	Send(ctx context.Context, msg []byte) error
	// Receive blocks and returns the next message from the connection.
	Receive(ctx context.Context) ([]byte, error)
	// Close closes the connection.
	Close() error
}

// Listener is the interface for accepting incoming connections.
type Listener interface {
	// Accept blocks until a new connection arrives.
	Accept(ctx context.Context) (Conn, error)
	// Close stops listening.
	Close() error
	// Addr returns the listener's network address.
	Addr() string
}

// Transport describes a transport implementation for registration.
type Transport struct {
	Name   string
	Dial   func(ctx context.Context, addr string) (Conn, error)
	Listen func(ctx context.Context, addr string) (Listener, error)
}

var registry = make(map[string]*Transport)

// Register registers a transport by name. Panics if name is empty, nil, or
// already registered.
func Register(t *Transport) {
	if t == nil {
		panic("grpc: Register called with nil Transport")
	}
	if t.Name == "" {
		panic("grpc: Register called with empty Name")
	}
	if _, exists := registry[t.Name]; exists {
		panic(fmt.Sprintf("grpc: duplicate transport name: %s", t.Name))
	}
	registry[t.Name] = t
}

// Get returns the registered Transport by name, or nil.
func Get(name string) *Transport {
	return registry[name]
}

func init() {
	Register(&Transport{
		Name:   "grpc",
		Dial:   Dial,
		Listen: Listen,
	})
}

// ---------------------------------------------------------------------------
// gRPC service skeleton (hand-written interface, no protoc dependency)
// ---------------------------------------------------------------------------

// XferMsg is the message type for the gRPC bidirectional stream.
// In production this would be generated from:
//
//	message XferMsg {
//	    bytes payload = 1;
//	}
type XferMsg struct {
	Payload []byte
}

// proto.Message 接口（手写——无 protoc 生成；bytes 字段直传）。
// 实现 MessageV1（Marshal/Unmarshal/Size）：grpc 反射检测到 Marshal 方法即用
// 自定义序列化（避免 protobuf 反射 marshaling 需要 protoimpl 注册）。
func (m *XferMsg) Reset()         { m.Payload = nil }
func (m *XferMsg) String() string { return "xfermsg" }
func (m *XferMsg) ProtoMessage()  {}

// Marshal 直接返回 payload 字节（bytes 字段直传）。
func (m *XferMsg) Marshal() ([]byte, error) { return m.Payload, nil }

// Unmarshal 直接取字节。
func (m *XferMsg) Unmarshal(b []byte) error {
	m.Payload = append([]byte(nil), b...)
	return nil
}

// Size 返回 payload 大小。
func (m *XferMsg) Size() int { return len(m.Payload) }

// Xfer_StreamClient is the client side of the Xfer.Stream bidirectional RPC.
// In production this would be generated by protoc.
type Xfer_StreamClient interface {
	Send(*XferMsg) error
	Recv() (*XferMsg, error)
	CloseSend() error
	Context() context.Context
}

// Xfer_StreamServer is the server side of the Xfer.Stream bidirectional RPC.
type Xfer_StreamServer interface {
	Send(*XferMsg) error
	Recv() (*XferMsg, error)
	Context() context.Context
}

// ---------------------------------------------------------------------------
// grpcConn wraps a gRPC bidirectional stream as a Conn.
// ---------------------------------------------------------------------------

// streamAPI 是流双向接口（客户端/服务端统一）。
type streamAPI interface {
	Send(*XferMsg) error
	Recv() (*XferMsg, error)
}

// grpcConn implements Conn over a gRPC bidirectional stream.
type grpcConn struct {
	stream  streamAPI
	closeFn func() error
}

// Send sends a message over the gRPC stream.
func (c *grpcConn) Send(ctx context.Context, msg []byte) error {
	return c.stream.Send(&XferMsg{Payload: msg})
}

// Receive blocks and returns the next message from the gRPC stream.
func (c *grpcConn) Receive(ctx context.Context) ([]byte, error) {
	msg, err := c.stream.Recv()
	if err != nil {
		return nil, err
	}
	return msg.Payload, nil
}

// Close closes the gRPC stream.
func (c *grpcConn) Close() error {
	if c.closeFn != nil {
		return c.closeFn()
	}
	return nil
}

// ---------------------------------------------------------------------------
// Dial and Listen (skeleton)
// ---------------------------------------------------------------------------

// Dial creates a new gRPC stream to the given address.
// addr 格式：host:port。用 insecure 凭据（传输层加密由上层 mux/隧道处理）。
func Dial(ctx context.Context, addr string) (Conn, error) {
	conn, err := grpc.NewClient(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, fmt.Errorf("grpc dial: %w", err)
	}
	desc := &grpc.StreamDesc{
		StreamName:    "Stream",
		ServerStreams: true,
		ClientStreams: true,
	}
	cs, err := conn.NewStream(ctx, desc, "/"+xferServiceName+"/Stream")
	if err != nil {
		conn.Close()
		return nil, fmt.Errorf("grpc dial stream: %w", err)
	}
	return &grpcConn{
		stream:  &clientStreamAdapter{cs},
		closeFn: func() error { _ = conn.Close(); return cs.CloseSend() },
	}, nil
}

// Listen starts a gRPC server on the given address and returns a Listener.
func Listen(ctx context.Context, addr string) (Listener, error) {
	ln, err := net.Listen("tcp", addr)
	if err != nil {
		return nil, fmt.Errorf("grpc listen: %w", err)
	}
	srv := grpc.NewServer()
	l := &grpcListener{srv: srv, ln: ln, ch: make(chan Xfer_StreamServer, 16)}
	srv.RegisterService(&xferServiceDesc, &xferServer{handler: func(stream Xfer_StreamServer) error {
		l.ch <- stream
		// 泵送由连接方接管；服务端等待 ctx 结束。
		<-stream.Context().Done()
		return stream.Context().Err()
	}})
	go func() {
		_ = srv.Serve(ln)
	}()
	return l, nil
}
